/** Explicit visual identities. Gameplay IDs and balance remain stable. */
export type CreatureShape = 'goblin' | 'slime' | 'boar' | 'mushroom' | 'beetle' | 'jackal' | 'sand' | 'scorpion' | 'gargoyle' | 'flame' | 'rogue' | 'bat' | 'spider' | 'cat' | 'wisp' | 'imp' | 'hound' | 'cultist' | 'golem' | 'harpy' | 'ram' | 'salamander' | 'drake' | 'worm' | 'scrap' | 'owl' | 'wyvern' | 'serpent' | 'knight' | 'ogre' | 'treant' | 'smith' | 'dragon';
export type CreatureIdentity = { shape: CreatureShape; description: string; asset?: 'Bat' | 'Goat' | 'Owl'; boss?: boolean };
const entry = (shape: CreatureShape, description: string, boss = false, asset?: CreatureIdentity['asset']): CreatureIdentity => ({ shape, description, boss, asset });
export const CREATURE_CATALOG: Record<string, CreatureIdentity> = {
  goblin: entry('goblin', 'Ушастый обитатель руин с коротким топором и кожаным поясом.'),
  slime: entry('slime', 'Округлое студенистое тело растекается у земли и пружинит при движении.'),
  boar: entry('boar', 'Коренастый лесной зверь с мощными клыками и жёсткой щетиной.'),
  mushroom: entry('mushroom', 'Живой гриб под широкой пятнистой шляпкой. Распространяет опасные споры.'),
  beetle: entry('beetle', 'Шестиногий жук с разделённым надвое панцирем и крепкими жвалами.'),
  'dust-jackal': entry('jackal', 'Длинноногий шакал с узкой мордой и острыми ушами.'),
  sandling: entry('sand', 'Оживший столб песчаника. Вокруг светящегося ядра парят обломки.'),
  'sun-scorpion': entry('scorpion', 'Пустынный скорпион с широкими клешнями и поднятым жалом.'),
  'ruin-gargoyle': entry('gargoyle', 'Крылатая каменная горгулья. Рога и когти высечены из той же породы, что и руины.'),
  emberling: entry('flame', 'Живая искра в оболочке из тлеющих углей.'),
  'shadow-bandit': entry('rogue', 'Разбойник в тёмном капюшоне. Вооружён парными клинками.'),
  'cave-bat': entry('bat', 'Крупный нетопырь с перепончатыми крыльями и длинными ушами.', false, 'Bat'),
  'venom-spider': entry('spider', 'Восьминогий паук с раздутым ядовитым брюшком и парой клыков.'),
  'cliff-stalker': entry('cat', 'Тёмный кошачий хищник с длинным хвостом. Держится у скальных троп.'),
  'dusk-wisp': entry('wisp', 'Блуждающий свет, окружённый кольцом осколков сумеречного камня.'),
  'fire-imp': entry('imp', 'Небольшой рогатый бес с крыльями, когтями и тонким хвостом.'),
  'magma-hound': entry('hound', 'Тяжёлая гончая с угольной шкурой и раскалённым гребнем.'),
  'obsidian-beetle': entry('beetle', 'Жук с острыми пластинами обсидиана на шестиногом теле.'),
  'cinder-cultist': entry('cultist', 'Человек в пепельной мантии с ритуальным посохом.'),
  'lava-elemental': entry('golem', 'Массивные глыбы удерживаются вместе раскалённым сердцем.'),
  harpy: entry('harpy', 'Крылатая женщина с оперёнными руками и цепкими птичьими лапами.'),
  'stone-elemental': entry('golem', 'Каменный великан с тяжёлыми кулаками и светящимися рунами.'),
  'mountain-cat': entry('cat', 'Светлый горный хищник с широкими лапами и гибким хвостом.'),
  'gale-spirit': entry('wisp', 'Спираль ветра вокруг парящего небесного кристалла.'),
  'cliff-ram': entry('ram', 'Горный козёл с высокими рогами и крепкими копытами.', false, 'Goat'),
  salamander: entry('salamander', 'Приземистая ящерица с широкими лапами и длинным огненным хвостом.'),
  'ash-cultist': entry('cultist', 'Заклинатель в закрытой мантии. Несёт посох с пепельным камнем.'),
  'ravine-scorpion': entry('scorpion', 'Багровый скорпион, прячущийся в трещинах русел.'),
  'crystal-wisp': entry('wisp', 'Парящий кристалл, вокруг которого вращаются маленькие призмы.'),
  'ember-drake': entry('drake', 'Молодой четырёхлапый дракон с рогатой головой и небольшими крыльями.'),
  'canyon-raider': entry('rogue', 'Налётчик в песчаном плаще и маске, вооружённый двумя клинками.'),
  'badland-jackal': entry('jackal', 'Сухопарый степной шакал с костяными отметинами на морде.'),
  'sand-worm': entry('worm', 'Бронированный червь с кольчатым телом и круглой зубастой пастью.'),
  'scrap-golem': entry('scrap', 'Собран из ржавых пластин, заклёпок и обломков механизмов.'),
  'dust-vulture': entry('owl', 'Пустынный филин с крупными глазами и рыжим оперением.', false, 'Owl'),
  'fire-cultist': entry('cultist', 'Служитель дракона в алой мантии с огненным навершием посоха.'),
  drake: entry('drake', 'Багровый дракон на четырёх лапах с длинным хвостом и короткими крыльями.'),
  wyvern: entry('wyvern', 'Двуногий крылатый ящер. Передние конечности образуют перепончатые крылья.'),
  'magma-serpent': entry('serpent', 'Длинный безногий змей с раскалённым гребнем и раздвоенным языком.'),
  'dragon-guard': entry('knight', 'Воин в чешуйчатой броне с рогатым шлемом, мечом и щитом.'),
  'moss-ogre': entry('ogre', 'Мшистый огр с широкой челюстью, массивными руками и тяжёлой дубиной.', true),
  'crystal-boar': entry('boar', 'Вепрь с кристаллическими наростами вдоль спины и огромными клыками.', true),
  'root-colossus': entry('treant', 'Древний ходячий дуб. Его руки — ветви, ноги — переплетённые корни.', true),
  'ash-matriarch': entry('scorpion', 'Древняя матриархиня скорпионов с широкими клешнями и тяжёлым жалом.', true),
  'prism-golem': entry('golem', 'Голем из призматических глыб с открытым сияющим ядром.', true),
  'sun-tyrant': entry('knight', 'Венценосный воин в солнечной броне с большим мечом и щитом.', true),
  'night-stalker': entry('cat', 'Крупный ночной хищник с гривой из тёмных шипов.', true),
  'venom-matriarch': entry('spider', 'Огромная восьминогая паучиха с ядовитым брюшком.', true),
  'pass-warden': entry('knight', 'Закованный в тяжёлую броню хранитель перевала.', true),
  'cinder-smith': entry('smith', 'Исполинский кузнец в кожаном фартуке с двуручным молотом.', true),
  'obsidian-beast': entry('hound', 'Могучий четырёхлапый зверь с гребнем из обсидиана.', true),
  'lava-golem': entry('golem', 'Исполин из чёрных глыб. Из трещин и открытого сердца льётся лава.', true),
  'storm-harpy': entry('harpy', 'Предводительница гарпий с широкими крыльями и венцом из перьев.', true),
  'stone-giant': entry('golem', 'Скальный исполин с плечами из огромных монолитов.', true),
  'sky-lord': entry('harpy', 'Крылатый владыка высокогорья с длинным оперением и светлым венцом.', true),
  'elder-salamander': entry('salamander', 'Древняя саламандра с огненным гребнем и тяжёлым хвостом.', true),
  'crystal-priest': entry('cultist', 'Высший жрец в кристальном венце с длинным ритуальным посохом.', true),
  'ash-serpent': entry('serpent', 'Огромный змей с пепельными чешуями и раскалённой пастью.', true),
  'raider-king': entry('rogue', 'Король налётчиков с короной и двумя широкими клинками.', true),
  'great-sand-worm': entry('worm', 'Исполинский песчаный червь с кольцами брони и венцом зубов.', true),
  'canyon-lord': entry('sand', 'Древний песчаный колосс, собравший тело из скал каньона.', true),
  'ancient-wyvern': entry('wyvern', 'Древняя двуногая виверна с широкими крыльями и длинными рогами.', true),
  'magma-serpent-lord': entry('serpent', 'Король магмовых змеев с костяным воротником и пылающим гребнем.', true),
  'fire-dragon': entry('dragon', 'Четырёхлапый огненный дракон. Огромные крылья, рогатая голова и шипастый хвост.', true),
};
export function creatureIdentity(id: string): CreatureIdentity {
  const identity = CREATURE_CATALOG[id];
  if (!identity) throw new Error(`Missing creature visual identity: ${id}`);
  return identity;
}
